import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
  // But you can create a sidebar manually

    tutorialSidebar: [
        {
            type: 'category',
            label: 'Getting Started',
            items: [
                'intro',
                'architecture',
                'getting-started',
            ],
        },
        {
            type: 'category',
            label: 'Computations',
            items: [
                'computations',
                'computation-logs',
                'roles',
                'assets',
            ],
        },
        {
            type: 'category',
            label: 'Cvms',
            items: [
                'cvms',
                'certs',
            ],
        },
        {
            type: 'category',
            label: 'User Management',
            items: [
                'access-control',
                'dashboard',
                'workspaces',
                'workspace-roles',
                'users',
                'invitations'
            ],
        },
        {
            type: 'category',
            label: 'API Reference',
            items: [
                'api',
                'assets_api_docs',
                'certs_api_docs',
                'computations_api_docs',
                'cvm_api_docs',
                'events_api_docs',
                'logs_api_docs'
            ]
        },
        "billing"
    ],
};

export default sidebars;
